__version__ = "0.2.0"

from .locator import CaptchaFontLocator
from .local_restore_types import (
    BucketSummary,
    LocalRestoreConfig,
    LocalRestoreStatus,
    LocalRestoreSummary,
    ProgressCallback,
    ProcessingErrorItem,
    StopChecker,
)
from .recognizer import CaptchaRecognizer
from .slider_locator import CaptchaSliderLocator
from .types import (
    BackgroundDeepFeatureResult,
    BackgroundRestoreResult,
    BackgroundTextureResult,
    BackgroundMeta,
    BatchGlyphExtractItem,
    BatchGlyphExtractResult,
    CaptchaType,
    CaptchaTypeLike,
    FontComponent,
    FontGlyph,
    FontGlyphExtractResult,
    FontGlyphFeature,
    FontGlyphFeatureExtractResult,
    FontGlyphImageExportResult,
    FontGlyphImageItem,
    FontGlyphSlot,
    FontGlyphSlotExtractResult,
    ForegroundSkewEstimateResult,
    GlyphDatasetExportResult,
    GlyphRenderMode,
    GlyphRenderModeLike,
    LocateResult,
    SliderGap,
    SliderLocateResult,
    TextLayerResult,
    TextLocateResult,
    TextRegion,
    normalize_captcha_type,
    normalize_glyph_render_mode,
)

# Neutral naming aliases (preferred for new users).
CaptchaVisionSDK = CaptchaRecognizer
CaptchaTextLocator = CaptchaFontLocator
CaptchaGapLocator = CaptchaSliderLocator

__all__ = [
    "__version__",
    "CaptchaRecognizer",
    "CaptchaVisionSDK",
    "CaptchaFontLocator",
    "CaptchaTextLocator",
    "CaptchaSliderLocator",
    "CaptchaGapLocator",
    "BackgroundTextureResult",
    "BackgroundDeepFeatureResult",
    "ForegroundSkewEstimateResult",
    "BackgroundRestoreResult",
    "BackgroundMeta",
    "CaptchaType",
    "CaptchaTypeLike",
    "GlyphRenderMode",
    "GlyphRenderModeLike",
    "normalize_captcha_type",
    "normalize_glyph_render_mode",
    "BatchGlyphExtractItem",
    "BatchGlyphExtractResult",
    "FontGlyph",
    "FontGlyphImageExportResult",
    "FontGlyphImageItem",
    "FontGlyphFeature",
    "FontGlyphFeatureExtractResult",
    "FontGlyphExtractResult",
    "FontGlyphSlot",
    "FontGlyphSlotExtractResult",
    "GlyphDatasetExportResult",
    "LocalRestoreConfig",
    "LocalRestoreStatus",
    "LocalRestoreSummary",
    "BucketSummary",
    "ProgressCallback",
    "StopChecker",
    "ProcessingErrorItem",
    "FontComponent",
    "LocateResult",
    "SliderGap",
    "SliderLocateResult",
    "TextRegion",
    "TextLocateResult",
    "TextLayerResult",
]
